"""init

Revision ID: dcb6023f11b6
Revises: 
Create Date: 2026-04-07 21:22:19.837938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb6023f11b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_browse_history_album_id', table_name='browse_history')
    op.drop_index('idx_browse_history_user_id', table_name='browse_history')
    op.drop_index('idx_browse_history_user_viewed', table_name='browse_history')
    op.drop_table('browse_history')
    op.drop_table('favorites')
    op.drop_index('idx_view_history_album_id', table_name='album_view_history')
    op.drop_index('idx_view_history_user_id', table_name='album_view_history')
    op.drop_index('idx_view_history_user_viewed', table_name='album_view_history')
    op.drop_table('album_view_history')
    op.drop_index('idx_favorites_album_id', table_name='user_favorites')
    op.drop_index('idx_favorites_user_album', table_name='user_favorites')
    op.drop_index('idx_favorites_user_id', table_name='user_favorites')
    op.drop_index('idx_user_favorites_album_id', table_name='user_favorites')
    op.drop_index('idx_user_favorites_user_id', table_name='user_favorites')
    op.drop_index('idx_user_favorites_user_album', table_name='user_favorites')
    op.create_index('idx_user_favorites_user_album', 'user_favorites', ['user_id', 'album_id'], unique=True)
    op.create_index(op.f('ix_user_favorites_album_id'), 'user_favorites', ['album_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.drop_index('idx_user_history_album_id', table_name='user_history')
    op.drop_index('idx_user_history_user_id', table_name='user_history')
    op.drop_index('idx_user_history_viewed_at', table_name='user_history')
    op.create_index(op.f('ix_user_history_album_id'), 'user_history', ['album_id'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_history_viewed_at'), 'user_history', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_history_viewed_at'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_album_id'), table_name='user_history')
    op.create_index('idx_user_history_viewed_at', 'user_history', ['viewed_at'], unique=False)
    op.create_index('idx_user_history_user_id', 'user_history', ['user_id'], unique=False)
    op.create_index('idx_user_history_album_id', 'user_history', ['album_id'], unique=False)
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_album_id'), table_name='user_favorites')
    op.drop_index('idx_user_favorites_user_album', table_name='user_favorites')
    op.create_index('idx_user_favorites_user_album', 'user_favorites', ['user_id', 'album_id'], unique=False)
    op.create_index('idx_user_favorites_user_id', 'user_favorites', ['user_id'], unique=False)
    op.create_index('idx_user_favorites_album_id', 'user_favorites', ['album_id'], unique=False)
    op.create_index('idx_favorites_user_id', 'user_favorites', ['user_id'], unique=False)
    op.create_index('idx_favorites_user_album', 'user_favorites', ['user_id', 'album_id'], unique=1)
    op.create_index('idx_favorites_album_id', 'user_favorites', ['album_id'], unique=False)
    op.create_table('album_view_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=False),
    sa.Column('viewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_view_history_user_viewed', 'album_view_history', ['user_id', 'viewed_at'], unique=False)
    op.create_index('idx_view_history_user_id', 'album_view_history', ['user_id'], unique=False)
    op.create_index('idx_view_history_album_id', 'album_view_history', ['album_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('browse_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=False),
    sa.Column('viewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_browse_history_user_viewed', 'browse_history', ['user_id', 'viewed_at'], unique=False)
    op.create_index('idx_browse_history_user_id', 'browse_history', ['user_id'], unique=False)
    op.create_index('idx_browse_history_album_id', 'browse_history', ['album_id'], unique=False)
    # ### end Alembic commands ###
